### ISSUE TITLE
591擋selenium

### ISSUE THREAD

**Issue by shunmin** [EasonLin0716/rent-crawlers#1]
最近591擋selenium, 連F12也擋，E神有解法不?

**Comment by OwenChen0911** [comment]
我用抓包軟體，也看不出甚麼
從靜態網頁只看得出用vue取資料

**Comment by EasonLin0716** [comment]
抱歉晚回覆了，這邊是我先前開發的觀察

591 是掛一個 timer 在 JavaScript 執行緒內監聽行為，除非找到該資源並 block 掉，否則應該沒有辦法阻止不了 timer 每幾秒執行一次的行為，也就是說反制擋 devtool 不太容易，如果我未來有研究出什麼 trick 會再分享出來。

至於 Selenium 被擋這點，八成也是掛 timer 去監聽某些事情。但因為它執行上畢竟是 JavaScript，我把 Selenium 中的 JavaScript disable 掉在跑看起來有解決掉，如果未來還有發生什麼奇怪行為也可以回報，PR 也歡迎提交

**Comment by EasonLin0716** [comment]
@shunmin 
我今天偶然發現了一個可以破除擋 F12 的方式供參
591 擋 F12 的原理是掛計時器偵測用戶是否開啟 Devtool
我們只要在開啟 Devtool 前把它的計時器全部清空就好
瀏覽器的部分可以新增一個書籤，方法如下：
https://blog.quantoyo.com/?p=384
JS 腳本很簡單：

```
javascript:(new Array(999).fill(0).forEach((_, i) => clearInterval(i)))
```

我在 Chrome 實測有效，如果你有需要的話再試試看
